{{- if .Values.followChangesForBranch }}
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/tags: git
  labels:
    app.kubernetes.io/version: "0.2"
    operator.tekton.dev/provider-type: community
  name: git-update-deployment
spec:
  description: This Task can be used to update image digest in a Git repo.
    It requires a secret with credentials for accessing the git repo.
  params:
  - name: GIT_REPOSITORY
    type: string
  - name: GIT_REF
    type: string
  - name: NEW_IMAGE
    type: string
  - name: NEW_DIGEST
    type: string
  - name: CONFIG_JSON_PATH
    type: string
  results:
  - description: The commit SHA
    name: commit
    type: string
  steps:
  - image: docker.io/alpine/git:v2.26.2
    name: git-clone
    resources: {}
    script: |
      rm -rf git-update-digest-workdir
      git clone $(params.GIT_REPOSITORY) -b $(params.GIT_REF) git-update-digest-workdir
    workingDir: $(workspaces.workspace.path)
  - image: docker.io/endeveit/docker-jq:latest
    name: set-image-tag
    resources: {}
    script: |
      cd git-update-digest-workdir/$(params.CONFIG_JSON_PATH)
      jq '.imageTag = "$(params.NEW_DIGEST)"' config.json > temp.json && mv temp.json config.json
    workingDir: $(workspaces.workspace.path)
  - image: docker.io/alpine/git:v2.26.2
    name: git-commit
    resources: {}
    script: |
      cd git-update-digest-workdir
      git config user.email "tektonbot@redhat.com"
      git config user.name "My Tekton Bot"

      git status
      git add git-update-digest-workdir/$(params.CONFIG_JSON_PATH)
      git commit -m "[ci] Image digest updated"

      git push

      RESULT_SHA="$(git rev-parse HEAD | tr -d '\n')"
      EXIT_CODE="$?"
      if [ "$EXIT_CODE" != 0 ]
      then
        exit $EXIT_CODE
      fi
      # Make sure we don't add a trailing newline to the result!
      echo -n "$RESULT_SHA" > $(results.commit.path)
    workingDir: $(workspaces.workspace.path)
  workspaces:
  - description: The workspace consisting of maven project.
    name: workspace
{{- end }}